apiVersion: v1
name: rancher-do-cluster-template
description: RKE2 Cluster template for DO
version: 0.1.0
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default