apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  {{- end }}
  kubernetesVersion: v1.21.10+rke2r1
  rkeConfig:
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      workerRole: true
      quantity: {{ .Values.nodepool.count }}
      name: {{ .Values.cluster.name }}-nodes
      machineConfigRef:
        kind: DigitaloceanConfig
        name: {{ .Values.cluster.name }}-nodes
      paused: false
      displayName: {{ .Values.cluster.name }}-nodes
    machineGlobalConfig:
      cni: calico
